kind: pipeline
name: build & publish develop

trigger:
  branch:
    - master

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: ghcr.io/maxbook/analytics
      registry: ghcr.io
      tags: ${DRONE_BRANCH}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
